# Generated by Django 3.0.7 on 2020-07-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_auto_20200712_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='middleNames',
            field=models.CharField(default='', max_length=100),
        ),
    ]
